
export const techOptions = [
    { value: "React", label: "React" },
    { value: "Vue", label: "Vue" },
    { value: "Angular", label: "Angular" },
    { value: "Node.js", label: "Node.js" },
    { value: "Express", label: "Express" },
    { value: "HTML", label: "HTML" },
    { value: "CSS", label: "CSS" },
    { value: "JavaScript", label: "JavaScript" },
    { value: "TypeScript", label: "TypeScript" },
    { value: "jQuery", label: "jQuery" },
    { value: "Bootstrap", label: "Bootstrap" },
    { value: "Sass", label: "Sass" },
    { value: "Less", label: "Less" },
    { value: "Tailwind CSS", label: "Tailwind CSS" },
    { value: "Django", label: "Django" },
    { value: "Flask", label: "Flask" },
    { value: "Ruby on Rails", label: "Ruby on Rails" },
    { value: "Spring Boot", label: "Spring Boot" },
    { value: "ASP.NET", label: "ASP.NET" },
    { value: "PHP", label: "PHP" },
    { value: "Laravel", label: "Laravel" },
    { value: "WordPress", label: "WordPress" },
    { value: "Drupal", label: "Drupal" },
    { value: "Magento", label: "Magento" },
    { value: "Vue.js", label: "Vue.js" },
    { value: "Next.js", label: "Next.js" },
    { value: "Nuxt.js", label: "Nuxt.js" },
    { value: "Gatsby", label: "Gatsby" },
    { value: "GraphQL", label: "GraphQL" },
    { value: "Apollo GraphQL", label: "Apollo GraphQL" },
    { value: "Redux", label: "Redux" },
    { value: "MobX", label: "MobX" },
    { value: "Webpack", label: "Webpack" },
    { value: "Rollup", label: "Rollup" },
    { value: "Babel", label: "Babel" },
    { value: "Jest", label: "Jest" },
    { value: "Mocha", label: "Mocha" },
    { value: "Chai", label: "Chai" },
    { value: "Cypress", label: "Cypress" },
    { value: "React Testing Library", label: "React Testing Library" },
    { value: "Enzyme", label: "Enzyme" },
    { value: "Storybook", label: "Storybook" },
    { value: "Swagger", label: "Swagger" },
    { value: "Postman", label: "Postman" },
    { value: "Git", label: "Git" },
    { value: "GitHub", label: "GitHub" },
    { value: "GitLab", label: "GitLab" },
    { value: "Bitbucket", label: "Bitbucket" },
    { value: "Docker", label: "Docker" },
    { value: "Kubernetes", label: "Kubernetes" },
    { value: "AWS", label: "AWS (Amazon Web Services)" },
    { value: "Azure", label: "Azure" },
    { value: "Google Cloud", label: "Google Cloud" },
    { value: "Heroku", label: "Heroku" },
    { value: "Netlify", label: "Netlify" },
    { value: "Firebase", label: "Firebase" },
    { value: "MongoDB", label: "MongoDB" },
    { value: "MySQL", label: "MySQL" },
    { value: "PostgreSQL", label: "PostgreSQL" },
    { value: "SQLite", label: "SQLite" },
    { value: "Redis", label: "Redis" },
    { value: "Elasticsearch", label: "Elasticsearch" },
    { value: "Kafka", label: "Kafka" },
    { value: "RabbitMQ", label: "RabbitMQ" },
    { value: "REST API", label: "REST API" },
    { value: "GraphQL", label: "GraphQL" },
    { value: "OAuth", label: "OAuth" },
    { value: "JWT", label: "JWT (JSON Web Token)" },
    
  ];
  